### ISSUE TITLE
Hardware Configuration

### ISSUE THREAD

**Issue by sniperc96** [divanoLetto/3D_STEP_Classification#1]
Hi, I want to run this project, but I'm worried that my computer's hardware performance is not enough to run this project. So, what is the recommended hardware configuration (cpu and graphics card) for this project? Can you share it? Thank you very much!

**Comment by divanoLetto** [comment]
Hi, the GCN network is not very deep so it shouldn't be necessary to have very powerful hardware. A lot depends on how big the STEP files you want to use as input. The settings I used for training are GPU: RTX 3070 laptop, RAM: 16GB, CPU: AMD Ryzen 7.

**Comment by sniperc96** [comment]
> Hi, the GCN network is not very deep so it shouldn't be necessary to have very powerful hardware. A lot depends on how big the STEP files you want to use as input. The settings I used for training are GPU: RTX 3070 laptop, RAM: 16GB, CPU: AMD Ryzen 7.

thany you for your reply!
